// Generated by Melange

import * as Stdlib__Array from "./array.mjs";

var init = Stdlib__Array.init;

var make_matrix = Stdlib__Array.make_matrix;

var append = Stdlib__Array.append;

var concat = Stdlib__Array.concat;

var sub = Stdlib__Array.sub;

var copy = Stdlib__Array.copy;

var fill = Stdlib__Array.fill;

var blit = Stdlib__Array.blit;

var to_list = Stdlib__Array.to_list;

var of_list = Stdlib__Array.of_list;

var iter = Stdlib__Array.iter;

var iteri = Stdlib__Array.iteri;

var map = Stdlib__Array.map;

var map_inplace = Stdlib__Array.map_inplace;

var mapi = Stdlib__Array.mapi;

var mapi_inplace = Stdlib__Array.mapi_inplace;

var fold_left = Stdlib__Array.fold_left;

var fold_left_map = Stdlib__Array.fold_left_map;

var fold_right = Stdlib__Array.fold_right;

var iter2 = Stdlib__Array.iter2;

var map2 = Stdlib__Array.map2;

var for_all = Stdlib__Array.for_all;

var exists = Stdlib__Array.exists;

var for_all2 = Stdlib__Array.for_all2;

var exists2 = Stdlib__Array.exists2;

var mem = Stdlib__Array.mem;

var memq = Stdlib__Array.memq;

var find_opt = Stdlib__Array.find_opt;

var find_index = Stdlib__Array.find_index;

var find_map = Stdlib__Array.find_map;

var find_mapi = Stdlib__Array.find_mapi;

var split = Stdlib__Array.split;

var combine = Stdlib__Array.combine;

var sort = Stdlib__Array.sort;

var stable_sort = Stdlib__Array.stable_sort;

var fast_sort = Stdlib__Array.fast_sort;

var to_seq = Stdlib__Array.to_seq;

var to_seqi = Stdlib__Array.to_seqi;

var of_seq = Stdlib__Array.of_seq;

var Floatarray = Stdlib__Array.Floatarray;

export {
  init ,
  make_matrix ,
  append ,
  concat ,
  sub ,
  copy ,
  fill ,
  blit ,
  to_list ,
  of_list ,
  iter ,
  iteri ,
  map ,
  map_inplace ,
  mapi ,
  mapi_inplace ,
  fold_left ,
  fold_left_map ,
  fold_right ,
  iter2 ,
  map2 ,
  for_all ,
  exists ,
  for_all2 ,
  exists2 ,
  mem ,
  memq ,
  find_opt ,
  find_index ,
  find_map ,
  find_mapi ,
  split ,
  combine ,
  sort ,
  stable_sort ,
  fast_sort ,
  to_seq ,
  to_seqi ,
  of_seq ,
  Floatarray ,
}
/* No side effect */
