// Generated by Melange

import * as Stdlib__List from "./list.mjs";

var length = Stdlib__List.length;

var compare_lengths = Stdlib__List.compare_lengths;

var compare_length_with = Stdlib__List.compare_length_with;

var is_empty = Stdlib__List.is_empty;

var cons = Stdlib__List.cons;

var hd = Stdlib__List.hd;

var tl = Stdlib__List.tl;

var nth = Stdlib__List.nth;

var nth_opt = Stdlib__List.nth_opt;

var rev = Stdlib__List.rev;

var init = Stdlib__List.init;

var append = Stdlib__List.append;

var rev_append = Stdlib__List.rev_append;

var concat = Stdlib__List.concat;

var flatten = Stdlib__List.flatten;

var equal = Stdlib__List.equal;

var compare = Stdlib__List.compare;

var iter = Stdlib__List.iter;

var iteri = Stdlib__List.iteri;

var map = Stdlib__List.map;

var mapi = Stdlib__List.mapi;

var rev_map = Stdlib__List.rev_map;

var filter_map = Stdlib__List.filter_map;

var concat_map = Stdlib__List.concat_map;

var fold_left_map = Stdlib__List.fold_left_map;

var fold_left = Stdlib__List.fold_left;

var fold_right = Stdlib__List.fold_right;

var iter2 = Stdlib__List.iter2;

var map2 = Stdlib__List.map2;

var rev_map2 = Stdlib__List.rev_map2;

var fold_left2 = Stdlib__List.fold_left2;

var fold_right2 = Stdlib__List.fold_right2;

var for_all = Stdlib__List.for_all;

var exists = Stdlib__List.exists;

var for_all2 = Stdlib__List.for_all2;

var exists2 = Stdlib__List.exists2;

var mem = Stdlib__List.mem;

var memq = Stdlib__List.memq;

var find = Stdlib__List.find;

var find_opt = Stdlib__List.find_opt;

var find_index = Stdlib__List.find_index;

var find_map = Stdlib__List.find_map;

var find_mapi = Stdlib__List.find_mapi;

var filter = Stdlib__List.filter;

var find_all = Stdlib__List.find_all;

var filteri = Stdlib__List.filteri;

var partition = Stdlib__List.partition;

var partition_map = Stdlib__List.partition_map;

var assoc = Stdlib__List.assoc;

var assoc_opt = Stdlib__List.assoc_opt;

var assq = Stdlib__List.assq;

var assq_opt = Stdlib__List.assq_opt;

var mem_assoc = Stdlib__List.mem_assoc;

var mem_assq = Stdlib__List.mem_assq;

var remove_assoc = Stdlib__List.remove_assoc;

var remove_assq = Stdlib__List.remove_assq;

var split = Stdlib__List.split;

var combine = Stdlib__List.combine;

var sort = Stdlib__List.sort;

var stable_sort = Stdlib__List.stable_sort;

var fast_sort = Stdlib__List.fast_sort;

var sort_uniq = Stdlib__List.sort_uniq;

var merge = Stdlib__List.merge;

var to_seq = Stdlib__List.to_seq;

var of_seq = Stdlib__List.of_seq;

export {
  length ,
  compare_lengths ,
  compare_length_with ,
  is_empty ,
  cons ,
  hd ,
  tl ,
  nth ,
  nth_opt ,
  rev ,
  init ,
  append ,
  rev_append ,
  concat ,
  flatten ,
  equal ,
  compare ,
  iter ,
  iteri ,
  map ,
  mapi ,
  rev_map ,
  filter_map ,
  concat_map ,
  fold_left_map ,
  fold_left ,
  fold_right ,
  iter2 ,
  map2 ,
  rev_map2 ,
  fold_left2 ,
  fold_right2 ,
  for_all ,
  exists ,
  for_all2 ,
  exists2 ,
  mem ,
  memq ,
  find ,
  find_opt ,
  find_index ,
  find_map ,
  find_mapi ,
  filter ,
  find_all ,
  filteri ,
  partition ,
  partition_map ,
  assoc ,
  assoc_opt ,
  assq ,
  assq_opt ,
  mem_assoc ,
  mem_assq ,
  remove_assoc ,
  remove_assq ,
  split ,
  combine ,
  sort ,
  stable_sort ,
  fast_sort ,
  sort_uniq ,
  merge ,
  to_seq ,
  of_seq ,
}
/* No side effect */
