// Generated by Melange

import * as Stdlib__Hashtbl from "./hashtbl.mjs";
import * as Stdlib__Map from "./map.mjs";
import * as Stdlib__Set from "./set.mjs";

var Hashtbl = Stdlib__Hashtbl;

var $$Map = Stdlib__Map;

var $$Set = Stdlib__Set;

export {
  Hashtbl ,
  $$Map ,
  $$Set ,
}
/* Stdlib__Hashtbl Not a pure module */
