// Generated by Melange

import * as Stdlib__String from "./string.mjs";

var make = Stdlib__String.make;

var init = Stdlib__String.init;

var empty = Stdlib__String.empty;

var of_bytes = Stdlib__String.of_bytes;

var to_bytes = Stdlib__String.to_bytes;

var concat = Stdlib__String.concat;

var cat = Stdlib__String.cat;

var equal = Stdlib__String.equal;

var compare = Stdlib__String.compare;

var starts_with = Stdlib__String.starts_with;

var ends_with = Stdlib__String.ends_with;

var contains_from = Stdlib__String.contains_from;

var rcontains_from = Stdlib__String.rcontains_from;

var contains = Stdlib__String.contains;

var sub = Stdlib__String.sub;

var split_on_char = Stdlib__String.split_on_char;

var map = Stdlib__String.map;

var mapi = Stdlib__String.mapi;

var fold_left = Stdlib__String.fold_left;

var fold_right = Stdlib__String.fold_right;

var for_all = Stdlib__String.for_all;

var exists = Stdlib__String.exists;

var trim = Stdlib__String.trim;

var escaped = Stdlib__String.escaped;

var uppercase_ascii = Stdlib__String.uppercase_ascii;

var lowercase_ascii = Stdlib__String.lowercase_ascii;

var capitalize_ascii = Stdlib__String.capitalize_ascii;

var uncapitalize_ascii = Stdlib__String.uncapitalize_ascii;

var iter = Stdlib__String.iter;

var iteri = Stdlib__String.iteri;

var index_from = Stdlib__String.index_from;

var index_from_opt = Stdlib__String.index_from_opt;

var rindex_from = Stdlib__String.rindex_from;

var rindex_from_opt = Stdlib__String.rindex_from_opt;

var index = Stdlib__String.index;

var index_opt = Stdlib__String.index_opt;

var rindex = Stdlib__String.rindex;

var rindex_opt = Stdlib__String.rindex_opt;

var to_seq = Stdlib__String.to_seq;

var to_seqi = Stdlib__String.to_seqi;

var of_seq = Stdlib__String.of_seq;

var blit = Stdlib__String.blit;

export {
  make ,
  init ,
  empty ,
  of_bytes ,
  to_bytes ,
  concat ,
  cat ,
  equal ,
  compare ,
  starts_with ,
  ends_with ,
  contains_from ,
  rcontains_from ,
  contains ,
  sub ,
  split_on_char ,
  map ,
  mapi ,
  fold_left ,
  fold_right ,
  for_all ,
  exists ,
  trim ,
  escaped ,
  uppercase_ascii ,
  lowercase_ascii ,
  capitalize_ascii ,
  uncapitalize_ascii ,
  iter ,
  iteri ,
  index_from ,
  index_from_opt ,
  rindex_from ,
  rindex_from_opt ,
  index ,
  index_opt ,
  rindex ,
  rindex_opt ,
  to_seq ,
  to_seqi ,
  of_seq ,
  blit ,
}
/* No side effect */
