// Generated by Melange

import * as Js__Caml_oo from "./caml_oo.mjs";
import * as Js__Curry from "./curry.mjs";

function js(label, cacheid, obj, args) {
  var meth = Js__Caml_oo.caml_get_public_method(obj, label, cacheid);
  return Js__Curry.app(meth, args);
}

function js1(label, cacheid, a0) {
  return Js__Curry._1(Js__Caml_oo.caml_get_public_method(a0, label, cacheid), a0);
}

function js2(label, cacheid, a0, a1) {
  return Js__Curry._2(Js__Caml_oo.caml_get_public_method(a0, label, cacheid), a0, a1);
}

function js3(label, cacheid, a0, a1, a2) {
  return Js__Curry._3(Js__Caml_oo.caml_get_public_method(a0, label, cacheid), a0, a1, a2);
}

function js4(label, cacheid, a0, a1, a2, a3) {
  return Js__Curry._4(Js__Caml_oo.caml_get_public_method(a0, label, cacheid), a0, a1, a2, a3);
}

function js5(label, cacheid, a0, a1, a2, a3, a4) {
  return Js__Curry._5(Js__Caml_oo.caml_get_public_method(a0, label, cacheid), a0, a1, a2, a3, a4);
}

function js6(label, cacheid, a0, a1, a2, a3, a4, a5) {
  return Js__Curry._6(Js__Caml_oo.caml_get_public_method(a0, label, cacheid), a0, a1, a2, a3, a4, a5);
}

function js7(label, cacheid, a0, a1, a2, a3, a4, a5, a6) {
  return Js__Curry._7(Js__Caml_oo.caml_get_public_method(a0, label, cacheid), a0, a1, a2, a3, a4, a5, a6);
}

function js8(label, cacheid, a0, a1, a2, a3, a4, a5, a6, a7) {
  return Js__Curry._8(Js__Caml_oo.caml_get_public_method(a0, label, cacheid), a0, a1, a2, a3, a4, a5, a6, a7);
}

export {
  js ,
  js1 ,
  js2 ,
  js3 ,
  js4 ,
  js5 ,
  js6 ,
  js7 ,
  js8 ,
}
/* No side effect */
