// Generated by Melange

import * as Js__Js_OO from "./js_OO.mjs";
import * as Js__Js_internal from "./js_internal.mjs";

var Obj = {};

var Js_OO = Js__Js_OO;

var Private = {
  Js_OO: Js_OO
};

var Fn = Js__Js_internal.Fn;

var Internal = Js__Js_internal.Internal;

export {
  Fn ,
  Internal ,
  Obj ,
  Private ,
}
/* No side effect */
